blank_issues_enabled: false
contact_links:
  - name: 📖 文档中心
    url: https://github.com/UNIkeEN/Amethyst-Launcher/docs
    about: 查看使用文档和常见问题解答
  - name: 💬 Discussions 讨论区
    url: https://github.com/UNIkeEN/Amethyst-Launcher/discussions
    about: 适合用于功能讨论、使用心得分享等非 Bug/非功能请求类话题
